from enum import Enum, unique


@unique
class UserStateKeys(Enum):

    SUBSCRIBING_DAILY_ALERT_PLACE = "SUBSCRIBING_DAILY_ALERT_PLACE"

    SUBSCRIBING_TRIGGER_ALERT_PLACE = "SUBSCRIBING_TRIGGER_ALERT_PLACE"

    SUBSCRIBING_NAME = "SUBSCRIBING_NAME"

    SUBSCRIBING_EMAIL = "SUBSCRIBING_EMAIL"

    SUBSCRIBING_PLACE = "SUBSCRIBING_PLACE"

    ALREADY_SUBSCRIBED = "ALREADY_SUBSCRIBED"

    EXPECTING_TRIGGER_TEMPERATURE = "EXPECT_TRIG_TEMP"

    EXPECTING_TRIGGER_CLOUDS = "EXPECT_TRIG_CLOUDS"

    EXPECTING_TRIGGER_HUMID = "EXPECT_TRIG_HUMID"


@unique
class UserDataKeys(Enum):

    CHAT_ID = "CHAT_ID"

    NAME = "NAME"

    EMAIL = "EMAIL"

    SUBSCRIBED_COORDS = "SUBSCRIBED_COORDS"

    NOTIFICATION_COORDS = "NOTIFICATION_COORDS"
    
    STATE = "STATE"

    LAST_UPDATE = "LAST_UPDATE"

    ALERT = "ALERT"

    WEATHER_ALERT_FLAVOR = "ALERT.TRIGGER.FLAVOR"

    WEATHER_ALERT_COND = "ALERT.TRIGGER.CONDITION"

    WEATHER_ALERT_VALUE = "ALERT.TRIGGER.VALUE"
