from enum import Enum, unique


@unique
class UserStateKeys(Enum):

    SUBSCRIBING_DAILY_ALERT_PLACE = "SUBSCRIBING_DAILY_ALERT_PLACE"

    SUBSCRIBING_TRIGGER_ALERT_PLACE = "SUBSCRIBING_TRIGGER_ALERT_PLACE"

    SUBSCRIBING_NAME = "SUBSCRIBING_NAME"

    SUBSCRIBING_EMAIL = "SUBSCRIBING_EMAIL"

    SUBSCRIBING_PLACE = "SUBSCRIBING_PLACE"

    EXPECTING_TRIGGER_TEMPERATURE = "EXPECTING_TRIGGER_TEMPERATURE"

    EXPECTING_TRIGGER_CLOUDS = "EXPECTING_TRIGGER_CLOUDS"

    EXPECTING_TRIGGER_HUMID = "EXPECTING_TRIGGER_HUMID"

    EXPECTING_DAILY_HOUR = "EXPECTING_DAILY_HOUR"


@unique
class UserDataKeys(Enum):

    NAME = "NAME"

    EMAIL = "EMAIL"

    SUBSCRIBED_COORDS = "SUBSCRIBED_COORDS"

    NOTIFICATION_COORDS = "NOTIFICATION_COORDS"
    
    STATE = "STATE"

    LAST_UPDATE = "LAST_UPDATE"

    ALERT = "ALERT"

    WEATHER_ALERT_FLAVOR = "ALERT.TRIGGER.FLAVOR"

    WEATHER_ALERT_COND = "ALERT.TRIGGER.CONDITION"

    WEATHER_ALERT_VALUE = "ALERT.TRIGGER.VALUE"

    WEATHER_TRIGGER_ALERT = "ALERT.TRIGGER"

    WEATHER_DAILY_ALERT = "ALERT.DAILY"
